pom.xml, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/ApiClientService.java, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/ApiClientServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/BaseApiClientServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
Dependant on 362, once merged will have main as base
Merge conflicts are expected since this is branched from main and not 362, merge conflicts will be fixed once 362 is merged into main
=> Insolvency consumer calls PUT insolvency endpoint

pom.xml, src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/InsolvencyMapper.java, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/test/java/uk/gov/companieshouse/insolvency/delta/mapper/InsolvencyMapperTest.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
Ticket: https://companieshouse.atlassian.net/browse/DSND-600
-Updated private-api-sdk-java version
-Updated Mapstruct mappings 
-Added updated_by field
-Updated unit tests
=> dsnd-600: Add additional Kafka headers and update insolvency mappings

pom.xml, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/ApiClientServiceImpl.java
Changes to call the /beta endpoint
=> Changes to call the /beta endpoint

src/itest/java/uk/gov/companieshouse/insolvency/delta/consumer/InsolvencyDeltaConsumerITest.java, src/main/java/uk/gov/companieshouse/insolvency/delta/consumer/InsolvencyDeltaConsumer.java, src/main/java/uk/gov/companieshouse/insolvency/delta/exception/NonRetryableErrorException.java, src/main/java/uk/gov/companieshouse/insolvency/delta/exception/RetryableErrorException.java, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/BaseApiClientServiceImpl.java, src/main/java/uk/gov/companieshouse/insolvency/delta/transformer/InsolvencyApiTransformer.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java, src/test/java/uk/gov/companieshouse/insolvency/delta/transformer/InsolvencyApiTransformerTest.java
Following exceptions must be raised (Acceptance criterias) - Comment added to each unit test for all criterias:
Avro Deserialization already tested in deserializer/serializer
=> DSND-423-unit tests to ensure retryable/non-retryable exceptions thrown

pom.xml, src/test/java/uk/gov/companieshouse/insolvency/delta/mapper/CaseMapperTest.java, src/test/java/uk/gov/companieshouse/insolvency/delta/mapper/InsolvencyMapperTest.java
DSND-729 Insolvency Data API - Changes after Case Number definition from integer to String
=> DSND-729 Insolvency Data API - Changes after Case Number definition

pom.xml
DSND-895 - Updated private SDK version in POM after moratorium was added
=> DSND-895 - Updated private SDK version in POM after moratorium was added

src/main/java/uk/gov/companieshouse/insolvency/delta/consumer/InsolvencyDeltaConsumer.java, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java
All log scenarios:
Each scenario is commented.
Resolves: https://companieshouse.atlassian.net/browse/DSND-636
=> Added context ID to all logs

src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/PractitionerAddressMapper.java
DSND-969 Staging-E2E-insolvency - Non mandatory address fields error when not present
=> DSND-969 Staging-E2E-insolvency - Non mandatory address fields error

src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/CaseMapper.java, src/test/java/uk/gov/companieshouse/insolvency/delta/mapper/CaseMapperTest.java
DSND-955 Staging-E2E-insolvency - practitioners field non existent when no appointments in the delta. Initialize practitioners if null after mapping
=> DSND-955 Staging-E2E-insolvency - practitioners field non existent 

pom.xml, src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/InsolvencyMapper.java, src/test/java/uk/gov/companieshouse/insolvency/delta/mapper/InsolvencyMapperTest.java, src/test/resources/insolvency-delta-complex.json
DSND-995 Implement missing logic to set the notes when jurisdiction is equal to 3 and the case_type is different than 'administration-order' or 'in-administration'.
=> DSND-995 Implement missing logic to set the notes

src/itest/resources/features/insolvency-delta-delete-flows.feature, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
=> DSND-929 - 410 on DELETE as a Non-retryable error

src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/CaseMapper.java
Code improvement for sonar qube
=> Code improvement for sonar qube

src/main/java/uk/gov/companieshouse/insolvency/delta/mapper/EncoderUtil.java
Excluding Sha1 code line for Sonar Qube
=> Excluding Sha1 code line for Sonar Qube

src/itest/resources/features/insolvency-delta-delete-flows.feature, src/main/java/uk/gov/companieshouse/insolvency/delta/service/api/BaseApiClientServiceImpl.java
DSND-1125 Addressing issue with 410 GONE that was incorrectly returning Retryable Exception
=> DSND-1125 Addressing issue with 410 GONE

Tiltfile.dev, pom.xml
Add a tiltfile for ch docker to the insolvency delta consumer for enhancements work
**Resolves**
DSND-1151
=> Add tiltfile for ch docker

src/itest/resources/features/insolvency-delta-error-retry.feature, src/itest/resources/input/case_type_15_with_any_date.json, src/main/java/uk/gov/companieshouse/insolvency/delta/constants/CaseNumberDatesMap.java
=> Add casenum 15 to validation map

src/itest/resources/features/insolvency-delta-delete-flows.feature, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
Insolvency - return a 404 response when a resource is not found
=> changed HTTP STATUS GONE to NOT FOUND

src/main/resources/application.yml
- Remove api.endpoint from **application.yml**
- Updated api.api-url to use the _INSOLVENCY_DATA_API_URL_ env var
=> DSND-1279 Update application.yml to use correct API_URL

src/itest/resources/features/insolvency-delta-delete-flows.feature, src/itest/resources/features/insolvency-delta-error-retry.feature, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
* Do not retry 400 and 409s.
* All other non 2xxs will be retried.
[DSND-2997](https://companieshouse.atlassian.net/browse/DSND-2997)
[DSND-2997]: https://companieshouse.atlassian.net/browse/DSND-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2997: Retry more http statuses

pom.xml, src/main/java/uk/gov/companieshouse/insolvency/delta/apiclient/ApiClient.java, src/main/java/uk/gov/companieshouse/insolvency/delta/apiclient/InsolvencyApiClient.java, src/main/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessor.java, src/test/java/uk/gov/companieshouse/insolvency/delta/apiclient/InsolvencyApiClientTest.java, src/test/java/uk/gov/companieshouse/insolvency/delta/processor/InsolvencyDeltaProcessorTest.java
[DSND-3115](https://companieshouse.atlassian.net/browse/DSND-3115)
[DSND-3115]: https://companieshouse.atlassian.net/browse/DSND-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3115: Add deltaAt to delete request handler

pom.xml
__Short description outlining key changes/additions__
__JU1155__
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__
=> correcting sonar dependency to resolve pipeline failure

pom.xml, src/itest/java/uk/gov/companieshouse/insolvency/delta/AbstractIntegrationTest.java, src/itest/java/uk/gov/companieshouse/insolvency/delta/CucumberFeaturesRunnerITest.java, src/itest/java/uk/gov/companieshouse/insolvency/delta/config/AbstractMongoConfig.java
__Correcting Integration Test__
__JU-1155__
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__
=> Correcting Integration Test

src/itest/java/uk/gov/companieshouse/insolvency/delta/config/KafkaTestContainerConfig.java, src/itest/java/uk/gov/companieshouse/insolvency/delta/config/WiremockTestConfig.java
__enhancements to make integration test run__
__JU-1155__
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__
=> enhancements to make integration test run

pom.xml, src/itest/java/uk/gov/companieshouse/insolvency/delta/config/KafkaTestContainerConfig.java
__enable integration test__
__JU-1155__
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__
=> enable integration test

terraform/groups/ecs-service/main.tf
set read_only_root_file_system to true and make secrets module 1.0.296 to match ecs module. This is for ecs security remediation.
=> set read_only_root_file_system to true

pom.xml
https://companieshouse.atlassian.net/browse/ASM-502
Adding latest sonar config to Pom
Using sonar-maven-plugin.version from parent pom
=> ASM-502 Add latest Sonar config to POM

ecs-image-build/docker_start.sh, terraform/groups/ecs-service/locals.tf
=> empty pr to rebuild
